# Generated by Django 5.1.7 on 2025-05-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantstatus',
            name='action',
            field=models.CharField(choices=[('WATER', 'Tưới nước'), ('FAN', 'Bật quạt'), ('LIGHT', 'Bật đèn'), ('FERTILIZE', 'Bón phân'), ('PRUNE', 'Tỉa cây'), ('NONE', 'Không có')], default='NONE', max_length=20),
        ),
    ]
